/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigureTypeRouteImport } from './routes/configure.$type'

const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureTypeRoute = ConfigureTypeRouteImport.update({
  id: '/configure/$type',
  path: '/configure/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quote': typeof QuoteRoute
  '/configure/$type': typeof ConfigureTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quote': typeof QuoteRoute
  '/configure/$type': typeof ConfigureTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quote': typeof QuoteRoute
  '/configure/$type': typeof ConfigureTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quote' | '/configure/$type'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quote' | '/configure/$type'
  id: '__root__' | '/' | '/quote' | '/configure/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuoteRoute: typeof QuoteRoute
  ConfigureTypeRoute: typeof ConfigureTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure/$type': {
      id: '/configure/$type'
      path: '/configure/$type'
      fullPath: '/configure/$type'
      preLoaderRoute: typeof ConfigureTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuoteRoute: QuoteRoute,
  ConfigureTypeRoute: ConfigureTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
