/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowTypesRouteImport } from './routes/window-types'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MeasureGuideRouteImport } from './routes/measure-guide'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuoteSuccessRouteImport } from './routes/quote.success'
import { Route as ConfigureTypeRouteImport } from './routes/configure.$type'

const WindowTypesRoute = WindowTypesRouteImport.update({
  id: '/window-types',
  path: '/window-types',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasureGuideRoute = MeasureGuideRouteImport.update({
  id: '/measure-guide',
  path: '/measure-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteSuccessRoute = QuoteSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => QuoteRoute,
} as any)
const ConfigureTypeRoute = ConfigureTypeRouteImport.update({
  id: '/configure/$type',
  path: '/configure/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/measure-guide': typeof MeasureGuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRouteWithChildren
  '/window-types': typeof WindowTypesRoute
  '/configure/$type': typeof ConfigureTypeRoute
  '/quote/success': typeof QuoteSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/measure-guide': typeof MeasureGuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRouteWithChildren
  '/window-types': typeof WindowTypesRoute
  '/configure/$type': typeof ConfigureTypeRoute
  '/quote/success': typeof QuoteSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/measure-guide': typeof MeasureGuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRouteWithChildren
  '/window-types': typeof WindowTypesRoute
  '/configure/$type': typeof ConfigureTypeRoute
  '/quote/success': typeof QuoteSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/measure-guide'
    | '/privacy-policy'
    | '/quote'
    | '/window-types'
    | '/configure/$type'
    | '/quote/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/measure-guide'
    | '/privacy-policy'
    | '/quote'
    | '/window-types'
    | '/configure/$type'
    | '/quote/success'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/measure-guide'
    | '/privacy-policy'
    | '/quote'
    | '/window-types'
    | '/configure/$type'
    | '/quote/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MeasureGuideRoute: typeof MeasureGuideRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QuoteRoute: typeof QuoteRouteWithChildren
  WindowTypesRoute: typeof WindowTypesRoute
  ConfigureTypeRoute: typeof ConfigureTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window-types': {
      id: '/window-types'
      path: '/window-types'
      fullPath: '/window-types'
      preLoaderRoute: typeof WindowTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measure-guide': {
      id: '/measure-guide'
      path: '/measure-guide'
      fullPath: '/measure-guide'
      preLoaderRoute: typeof MeasureGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/success': {
      id: '/quote/success'
      path: '/success'
      fullPath: '/quote/success'
      preLoaderRoute: typeof QuoteSuccessRouteImport
      parentRoute: typeof QuoteRoute
    }
    '/configure/$type': {
      id: '/configure/$type'
      path: '/configure/$type'
      fullPath: '/configure/$type'
      preLoaderRoute: typeof ConfigureTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QuoteRouteChildren {
  QuoteSuccessRoute: typeof QuoteSuccessRoute
}

const QuoteRouteChildren: QuoteRouteChildren = {
  QuoteSuccessRoute: QuoteSuccessRoute,
}

const QuoteRouteWithChildren = QuoteRoute._addFileChildren(QuoteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MeasureGuideRoute: MeasureGuideRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QuoteRoute: QuoteRouteWithChildren,
  WindowTypesRoute: WindowTypesRoute,
  ConfigureTypeRoute: ConfigureTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
